name: base-compose

services:
  mongo:
    image: mongodb/mongodb-community-server:7.0-ubi9
    healthcheck: &health
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    expose:
      - 27017
  redis:
    image: redis/redis-stack
    healthcheck:
      <<: *health
      test: ["CMD", "redis-cli", "ping"]
    expose:
      - 6793
      - 8001
